restserver:
  addr : ":8080"
  pprofenable: 0
  username: "Y2ltcmktdXNlcm5hbWU="
  password: "c2NSRlRXNVJvVEFVOENJTHE2VWtrUQ=="

redis:
  address: "redis:6379"
  keyprefix: ""
  username: ""
  password: ""

loggerconfig:
  appname : "case-study-api-service"
  loglevel : 0
  logencoding : "json"
  environmenttype : "production"